_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "SSRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 10
  SS:
    FEAT_LEVEL: "res4"
    NAME: ["build_rotation_head"]
    LOSS_SCALE: 0.5
    RATIO: 2.0
DATASETS:
  TRAIN_SOURCE: ("cityscapes_train",)
  TRAIN_TARGET: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_foggy_val",)
SOLVER:
  # the size of the BDD tracking daytime is about 2x of the BDD100k dataset
  # for initial experiments, this schedule will be approximately, 0.5X schedule
  # ~5 epochs
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (6000, 8000,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (800,)
  CROP:
    ENABLED: True
OUTPUT_DIR: "checkpoints/uda/city2foggy/R50_FPN_rot"