MODEL:
  WEIGHTS: "./checkpoints/vgg_d2.pkl"
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  VGG:
    DEPTH: 16
  ANCHOR_GENERATOR:
    SIZES: [[128, 256, 512]]
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    IN_FEATURES: ['vgg_block5']
  ROI_HEADS:
    NAME: "VggROIHeads"
    IN_FEATURES: ['vgg_block5']
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
DATASETS:
  TRAIN: ("cityscapes_train",)
  TEST: ("cityscapes_foggy_val",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.005
  STEPS: (12000, 16000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
OUTPUT_DIR: "checkpoints/uda/city2foggy/vgg_sourceonly"